In [2]:
import pandas as pd

df = pd.read_csv("Data/Cleaned/final_dataset.csv")
df.head()
df.columns.tolist()
df.shape
df.isnull().sum().sort_values(ascending=False).head(20)

AnimalName            1321
DogAgeGroup            343
ApproxDogAge            97
AnimalGender             0
AnimalBirthYear          0
BreedName                0
ZipCode                  0
LicenseIssuedDate        0
LicenseExpiredDate       0
Extract Year             0
IssueYear                0
ExpireYear               0
IsBadName                0
CleanedBreedName         0
dtype: int64

In [3]:
year_counts = (
    df.groupby("IssueYear")
      .size()
      .reset_index(name="license_count")
      .sort_values("IssueYear")
)
year_counts.head()

   IssueYear  license_count
0       2014           1535
1       2015          34371
2       2016          76360
3       2017          73584
4       2018          71757

In [5]:
older_dogs = df[df["DogAgeGroup"].isin(["7–10 (Senior)", "10+ (Elderly)"])]
older_dogs

,AnimalName,AnimalGender,AnimalBirthYear,BreedName,ZipCode,LicenseIssuedDate,LicenseExpiredDate,Extract Year,ApproxDogAge,DogAgeGroup,IssueYear,ExpireYear,IsBadName,CleanedBreedName
20,OTIS,F,2001.0,Unknown,10011,2014-09-13,2017-09-29,2016,13.0,10+ (Elderly),2014,2017,False,Unknown
23,LOGAN,M,2003.0,Unknown,10011,2014-09-13,2017-10-30,2016,11.0,10+ (Elderly),2014,2017,False,Unknown
66,ANGEL,M,2000.0,Bichon Frise,10467,2014-09-15,2017-10-31,2016,14.0,10+ (Elderly),2014,2017,False,Bichon Frise
68,SABRINA,F,2002.0,Unknown,11106,2014-09-16,2017-09-30,2016,12.0,10+ (Elderly),2014,2017,False,Unknown
77,JUPLAY,M,2002.0,Beagle,11106,2014-09-16,2017-10-23,2016,12.0,10+ (Elderly),2014,2017,False,Beagle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546670,POGACS,F,2010.0,Puli,11109,2024-12-31,2025-12-24,2024,14.0,10+ (Elderly),2024,2025,False,Puli
546671,BRUTUS,M,2013.0,Rottweiler,10314,2024-12-31,2025-12-31,2024,11.0,10+ (Elderly),2024,2025,False,Rottweiler
546673,RUBY,F,2013.0,American Pit Bull Mix / Pit Bull Mix,11221,2024-12-31,2026-02-14,2024,11.0,10+ (Elderly),2024,2026,False,American Pit Bull Terrier Mix
546675,FRED,M,2010.0,Unknown,10304,2024-12-31,2025-12-30,2024,14.0,10+ (Elderly),2024,2025,False,Unknown
546715,SALLY,F,2013.0,Labrador Retriever Mix,11215,2024-12-31,2026-01-08,2024,11.0,10+ (Elderly),2024,2026,False,labrador retriever